### ISSUE TITLE
modifiche

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/HTML#2]
prova a fare queste modifiche:
righe 16 e seguenti metti in evidenza "alto livello", "basso livello" e "medio livello"
riga 22 ANSI è un'abbreviazione
riga 70 The C Programming Language è una citazione
rige 101 e seguenti è un codice

**Comment by CarloRuzzon** [comment]
prof mi dovete inviare i file di html 2 altrimenti non posso proseguire

2016-11-06 17:00 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
``` html
<abbr>      abbreviazioni
<acronym>   acronimi
<cite>      citazioni
<code>      codice sorgente
<dfn>       termini da definire
<em>        evidenza
<strong>    evidenza forte
<kbd>       da inserire con la tastiera
<samp>      testo di esempio
<var>       variabili
<pre>       testo preformattato
<address>   dati di contatto
```

**Comment by CarloRuzzon** [comment]
fatto

**Comment by FabioZTessitore** [comment]
quasi bene:

imperfezione nella spaziatura `libro<cite> The C Programming Language è una citazione</cite>`

errore sul codice. Il titolo non fa parte del codice

**Comment by CarloRuzzon** [comment]
risolto
