### ISSUE TITLE
Tweets

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/HTML#3]
Dai un'occhiata al file posts.html e
crea una pagina tweets.html in cui sia presente
una lista di tweets. Scegli con attenzione gli
elementi di cui e' formato un singolo tweet.

**Comment by CarloRuzzon** [comment]
Professò controllate se è quello che avete chiesto

**Comment by FabioZTessitore** [comment]
va bene ma non ti sei sprecato proprio per trovare altri elementi haha
